using System;
using System.Reflection;
using UnityEngine;
using Unity.Netcode;
using HarmonyLib;

namespace CompetitivePuckTweaks.src
{

    // old function: for goalie stick reach limit

    // [HarmonyPatch(typeof(StickPositioner), "PositionBladeTarget")]
    // public class StickControllerFixedUpdatePatch
    // {
    //     [HarmonyPostfix]
    //     public static void Postfix(StickPositioner __instance, ref float ___maximumReach)
    //     {
    //         if (__instance.Player.Role.Value == PlayerRole.Goalie)
    //         {
    //             if (__instance.PlayerBody.IsSliding.Value)
    //             {
    //                 ___maximumReach = PluginCore.config.GoalieMaximumReach;
    //                 Vector3 playerProjection = Vector3.ProjectOnPlane(__instance.Stick.PlayerBody.transform.forward, Vector3.up);
    //                 Vector3 stickProjection = Vector3.ProjectOnPlane(__instance.Stick.transform.forward, Vector3.up);
    //                 float angle = Vector3.Angle(playerProjection, stickProjection);
    //                 ___maximumReach -= Mathf.Clamp((90 - angle) * 0.01f, 0f, PluginCore.config.GoalieReachDropoff);
    //             }
    //             else
    //             {
    //                 ___maximumReach = 2.5f; // Normal reach for non-sliding goalies
    //             }
    //         }
    //     }
    // }

    [HarmonyPatch(typeof(StickPositioner), "Awake")]
    public class StickPositionerAwakePatch
    {
        [HarmonyPostfix]
        public static void Postfix(StickPositioner __instance, ref float ___softCollisionForce, ref Vector3 ___bladeTargetFocusPointInitialLocalPosition, ref float ___outputMin, ref float ___outputMax, ref float ___proportionalGain, ref float ___integralGain, ref float ___derivativeGain)
        {
            ___softCollisionForce = PluginCore.config.SoftCollisionForce;
            ___bladeTargetFocusPointInitialLocalPosition += new Vector3(0, PluginCore.config.BladeTargetFocusPointOffsetY, 0);
            // if (PluginCore.config.AlterStickPositionerOutput)
            // {
            //     float newOutput = PluginCore.config.StickPositionerOutputMax;
            //     if (__instance.PlayerBody.Player.Role.Value == PlayerRole.Goalie) newOutput = PluginCore.config.GoaliePositionerOutputMax;

            //     ___outputMin = -newOutput;
            //     ___outputMax = newOutput;
            // }

            if (PluginCore.config.EnableStickSpeedDecay) __instance.gameObject.AddComponent<FloatComponent>();
        }
    }

    [HarmonyPatch(typeof(StickPositioner), "FixedUpdate")]
    public class StickFixedUpdatePatch
    {
        [HarmonyPostfix]
        public static void Postfix(StickPositioner __instance, ref float ___outputMin, ref float ___outputMax)
        {
            float defaultValue = __instance.Player.Role.Value == PlayerRole.Goalie ? PluginCore.config.GoaliePositionerOutputMax : PluginCore.config.StickPositionerOutputMax;

            if (!PluginCore.config.AlterStickPositionerOutput) return;
            else if (!PluginCore.config.EnableStickSpeedDecay)
            {
                ___outputMin = -defaultValue;
                ___outputMax = defaultValue;
                return;
            }

            FloatComponent runningAvg = __instance.gameObject.GetComponent<FloatComponent>();

            runningAvg.value += ((__instance.Stick.Rigidbody.GetPointVelocity(__instance.Stick.BladeHandlePosition) - __instance.PlayerBody.Rigidbody.linearVelocity).magnitude - runningAvg.value) / PluginCore.config.StickSpeedDecaySpan;

            if (runningAvg.value > PluginCore.config.StickSpeedDecayLimit && ___outputMax > PluginCore.config.StickSpeedDecayMin)
            {
                ___outputMin += PluginCore.config.StickSpeedDecayRate * (runningAvg.value - PluginCore.config.StickSpeedDecayLimit);
                ___outputMax = -___outputMin;
            }
            else if (___outputMax < defaultValue)
            {
                ___outputMin = Mathf.Min(___outputMin - 20f, defaultValue);
                ___outputMax = -___outputMin;
            }
        }
    }

    // John's board bounce adjustments patch

    // Harmony patch to reduce linear acceleration from StickPositioner.ApplySoftCollision
    // while preserving the torque generated by AddForceAtPosition. This uses the
    // "cancel at COM" method: after the original AddForceAtPosition runs we apply
    // an opposite force at the Rigidbody COM equal to a fraction of the contact
    // force, leaving the torque unchanged.

    [HarmonyPatch(typeof(StickPositioner), "ApplySoftCollision")]
    static class BoardBounceAdjustments_Patch
    {
        // Local configurable defaults — do not rely on ValueTweaks for these.
        // Fraction of the soft-collision linear force to cancel at the Rigidbody COM (0..1).
        // 0 = do not cancel (original behavior). 1 = cancel all linear component (pure rotation).
        public static float SoftCollisionLinearReduction = PluginCore.config.JohnBoardBounceLinearReduction;
        // Fallback soft collision force used if reflection cannot read the instance field.
        public static float SoftCollisionForceDefault = PluginCore.config.JohnBoardBounceDefaultForce;
        // Enable debug logging for adjustments (may be chatty)
        public static bool DebugLogging = false;
        
        [HarmonyPostfix]
        public static void Postfix(StickPositioner __instance, RaycastHit hit, Vector3 hitPosition)
        {
            try
            {
                if (__instance == null) return;
                // Only run on server (physics authority)
                if (NetworkManager.Singleton == null || !NetworkManager.Singleton.IsServer) return;

                // Get PlayerBody Rigidbody
                var playerBody = __instance.PlayerBody;
                if (playerBody == null) return;
                var rb = playerBody.Rigidbody;
                if (rb == null) return;

                // Read configurable reduction fraction from this patch's local config
                float reduction = Mathf.Clamp(SoftCollisionLinearReduction, 0f, 1f);
                if (reduction <= 0f) return; // nothing to do

                // Recompute the contact force used in ApplySoftCollision to match the original
                // F = hit.normal * d * (softCollisionForce * num)
                float maximumReach = 0f;
                GameObject raycastOrigin = null;
                float softCollisionForce = SoftCollisionForceDefault;
                try
                {
                    var t = __instance.GetType();

                    var fi = t.GetField("maximumReach", BindingFlags.Instance | BindingFlags.NonPublic);
                    if (fi != null) maximumReach = (float)fi.GetValue(__instance);
                    else
                    {
                        var pi = t.GetProperty("maximumReach", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                        if (pi != null) maximumReach = (float)pi.GetValue(__instance);
                    }

                    var fi2 = t.GetField("raycastOrigin", BindingFlags.Instance | BindingFlags.NonPublic);
                    if (fi2 != null) raycastOrigin = (GameObject)fi2.GetValue(__instance);
                    else
                    {
                        var pi2 = t.GetProperty("raycastOrigin", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                        if (pi2 != null) raycastOrigin = (GameObject)pi2.GetValue(__instance);
                    }

                    var fi3 = t.GetField("softCollisionForce", BindingFlags.Instance | BindingFlags.NonPublic);
                    if (fi3 != null) softCollisionForce = (float)fi3.GetValue(__instance);
                    else
                    {
                        var pi3 = t.GetProperty("softCollisionForce", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                        if (pi3 != null) softCollisionForce = (float)pi3.GetValue(__instance);
                    }
                }
                catch { }

                // If maximumReach wasn't found via reflection, fall back to an estimate using hit.distance
                float d = maximumReach - hit.distance;
                // If raycastOrigin is present, use it to compute the original magnitude factor; otherwise estimate
                float magnitude = 0f;
                try
                {
                    if (raycastOrigin != null)
                    {
                        magnitude = Vector3.Cross(hit.normal, raycastOrigin.transform.forward).magnitude;
                    }
                    else
                    {
                        // fallback: approximate using hit.normal and player's forward
                        var pl = __instance.transform;
                        magnitude = Vector3.Cross(hit.normal, pl.forward).magnitude;
                    }
                }
                catch { magnitude = 0f; }



                float num = 1f - magnitude;
                float effectiveSoft = softCollisionForce;

                // Build the exact force vector used by ApplySoftCollision
                Vector3 F = hit.normal * d * (effectiveSoft * num);

                // Compute cancelling force to apply at COM
                Vector3 cancel = -reduction * F;

                // Apply cancellation at COM using same ForceMode (Acceleration) used by ApplySoftCollision
                try
                {
                    rb.AddForce(cancel, ForceMode.Acceleration);

                    try { if (DebugLogging) Debug.Log($"[BoardBounceAdjustments] Cancelled {reduction * 100f}% of soft collision linear force: cancel={cancel}"); } catch { }
                }
                catch (Exception e)
                {
                    try { Debug.LogException(e); } catch { }
                }
            }
            catch (Exception e)
            {
                try { Debug.LogException(e); } catch { }
            }
        }
    }
}